### ISSUE TITLE
If some Deferred using as value of second Deferred - not need call callback of second Deferred

### ISSUE THREAD

**Issue by Gvozd** [my8bird/nodejs-twisted-deferreds#2]
Hello.
Sorry for my very bad english.

I have a code like this:

``` javascript
var twisted = require('twisted-deferred');
var a = new twisted.Deferred();
a.addCallbacks(function(a) {
    console.log('a = ' + a);
});
var b = new twisted.Deferred();
b.addCallbacks(function(b) {
    console.log('b = ' + b);
});
console.log('start');
a.callback(b);
console.log('process');
b.callback(123)
console.log('end');
```

And I expect as result this:

```
start
process
b = 123
a = 123
end
```

But keep this:

```
start
a = [object Object]
process
b = 123
end
```

In other words, if i set value to Deferred _a_ as another Deferred _b_, not need call callback for _a_, until b is unknown

I believe that tцisted and works, but I could be wrong

**Comment by my8bird** [comment]
What you are trying to do is incorrect and will raise an exception in python twisted (see below for the correct method).
Here is a python port of what you are doing::

```
from twisted.internet import reactor, defer

def callback_a(value):
   print "a = " + value

def callback_b(value):
   print "b = " + value

a = defer.Deferred()
a.addCallback(callback_a)

b = defer.Deferred()
b.addCallback(callback_b)

print 'start'
a.callback(b)
print 'process'
b.callback(123)
print 'end'

# manually set up the end of the process by asking the reactor to
# stop itself in 4 seconds time
reactor.callLater(4, reactor.stop)
# start up the Twisted reactor (event loop handler) manually
reactor.run()
```

Result:

```
assert not isinstance(result, Deferred) # This assertion is raised inside twisted.
```

The issue is that Deferred's can not be the starting value for the callback chain.  To do what you are proposing you would want to use Deferred.chainDeferred or simply wait for the (b) Deferred to have its callback fired.

A slight change to your initial node code that should work.

```
var a = new twisted.Deferred();
a.addCallbacks(function(val) {
    console.log('a = ' + val);
    return val;
});
var b = new twisted.Deferred();
b.addCallbacks(function(val) {
    console.log('b = ' + val);
    return val;
});
console.log('start');
b.chainDeferred(a)
a.callback(b);
console.log('process');
b.callback(123)
console.log('end');
```

Also, note that there was a bug in chainDeferred that i just fixed so be sure to update your install.  you should get 0.2.0 if you want this fix.  For part of this fix I bound all of the Deferred's methods so that they can be passed around easily.

**Comment by Gvozd** [comment]
Thanks a lot for your answer
Now I see that I was wrong

I previously did not know about chainDeferred()

**Comment by my8bird** [comment]
and thanks to you a bug got fixed

On Jan 22, 2012, at 6:55 PM, Gvozd
reply@reply.github.com
wrote:
